box:
  php: '7'
  name: 'dreambox'

sites:
  'dreambox':
    username: db_user
    web_root: dreambox.com
    local_root: web
    hosts:
      - dreambox.test
      - www.dreambox.test
    ssl: true
debug: true
