name: 'dreambox'
php: '7'
ssl: true
# host: main-host.dev

sites:
  'dreambox':
    username: 'db_user' # required
    uid: 31415 # HACK
    root: 'dreambox.com' # required
    public: 'public'
    local_root: 'web/' # required
    host: 'www.dreambox.test' # required
    aliases:
      - 'dreambox.test'
    subdomains:
      app: 'app/'
    # ssl: true
  'example':
    username: example_user
    uid: 31416 # HACK
    root: example.com
    local_root: web
    host: example.dev
    subdomains: { 'help': '/app/help/' }
    ssl: false

# debug: true
