name: 'dreambox'
# php: '7'
# ssl: true

sites:
  'dreambox':
    user: 'db_user' # required
    root: 'dreambox.com' # required
    # public: 'public'
    local_root: 'static/' # required
    host: 'www.dreambox.test' # required
    # aliases:
    #   - 'dreambox.test'
    # subdomains:
    #   app: 'app/'
  # 'example':
  #   user: example_user
  #   root: example.com
  #   local_root: web
  #   host: example.dev
  #   subdomains: { 'help': '/app/help/' }
  #   ssl: false

# debug: true
